cuda_compiler: # [linux64]
  - cuda-nvcc # [linux64]
torch_version:
  - 2.3.1 # [linux64]
  - 2.4 # [linux64]
python_version:
  - 3.10
  - 3.11
cuda_compiler_version: # [linux64]
  - 12.0 # [linux64]
mpi:
  - mpich
  - openmpi